### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by Farida-Hamid**
### Make the website more accessible:

- Page titles: Changed to a more telling title.
- Image text alternatives: Removed the alternative text from programming languages as they are explained. No issues were found with the rest of the images.
- Text headings: Include only one `header1`.
- Color contrast:
- Resize: no issues found.
Interaction:
- Moving content: no moving content.
- Multimedia: no multimedia.
- The basic structure of the page: no issues found.

### CODE REVIEW

**Review by AnselemOdims — APPROVED** [review]
### Hi  @Farida-Hamid 🙋‍♀️, 
Good job implementing all the project requirements for this milestone/project.
This is an approval for application deploy as I can see you have included it in the README file.

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bellom** [comment]
@Farida-Hamid - Kindly list all points that you have checked as we have it stated in the [project requirement ](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md#:~:text=List%20all%20points%20that%20you%20have%20checked%2C%20i.e%3A) and If everything is ok, make a statement about that (e.g. "Page titles - no issues found").

CR Leader.

**Comment by bellom** [comment]
Hi @Farida-Hamid, as I mentioned in my previous comment, kindly list all points with results as we have them in the screenshot below, you should have a total of 9 checks;

image

Good job 👍 , after reviewing your website, you have just 2 issues to fix, kindly work on the following issues below:

**Contrast check:** There are 4 errors. kindly share a screenshot of your result if you're not using this [tool](https://www.aditus.io/button-contrast-checker/)

**Header check:** There are 2 issues (You have two h1 tags)

Kindly work on this and drop a comment on this PR 👍 .

**Comment by Farida-Hamid** [comment]
> Hi @bellom 
**Thanks a lot for your continuous help.**

## The Contrast checks errors are for elements consistent with the Figma design:
Screen Shot 2022-05-12 at 6 02 22 PM
Screen Shot 2022-05-12 at 6 02 44 PM
Screen Shot 2022-05-12 at 6 02 58 PM
Screen Shot 2022-05-12 at 6 03 15 PM

**Please tell me if we have to change the colors.**

**Comment by bellom** [comment]
@Farida-Hamid, Please confirm you're using the exact code from the Figma?

Once you click on a particular element in the Figma, you will see lines of CSS code displayed at the right, shown in the screenshot below;

image


Make sure you're using the same thing, you won't get errors if you're using the same exact CSS code.

**Comment by Farida-Hamid** [comment]
Hi @bellom 
Thank you for your feedback and patience. My apologies for dragging it this long.

I changes the colors of the elements that failed the test, except for the logo element. I made sure that my code matches the Figma design. I don't know why it failed the contrast test.

Screen Shot 2022-05-13 at 3 23 12 PM

**In the Figma design:**
Screen Shot 2022-05-13 at 2 50 23 PM

**In my code:**
Screen Shot 2022-05-13 at 2 51 51 PM

**Comment by bellom** [comment]
@Farida-Hamid - I will look into this and revert, to confirm with you, do you test with your live demo link? and I hope you re-deploy before testing.

**Comment by Farida-Hamid** [comment]
Thanks, @bellom.
No, I did not merge. I thought should merge the pull request after your approval.

**Comment by bellom** [comment]
@Farida-Hamid - I mean you should deploy on GH not merge.
And also check out this button specification on Figma which focuses on buttons types;

I can see you're using the same color now, no worries. kindly deploy again.

**Comment by bellom** [comment]
@Farida-Hamid - Yes, you can 🙂, and I can see it's working fine, I can see your latest changes in the new deployment live link.

This PR would be approved soon.

**Comment by Farida-Hamid** [comment]
Thanks, @bellom. You've been very helpful 🙏

**Pull request merged**
